-- CreateTable
CREATE TABLE "USUARIO_SISTEMA" (
    "ID_USUARIO" TEXT NOT NULL,
    "LOGIN_USUARIO" TEXT NOT NULL,
    "SENHA_USUARIO" TEXT NOT NULL,
    "EMAIL_USUARIO" TEXT NOT NULL,

    CONSTRAINT "USUARIO_SISTEMA_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "EMPRESA" (
    "ID_EMPRESA" TEXT NOT NULL,
    "DESCRICAO_EMPRESA" TEXT NOT NULL,
    "DOCUMENTO_EMPRESA" TEXT NOT NULL,

    CONSTRAINT "EMPRESA_pkey" PRIMARY KEY ("ID_EMPRESA")
);

-- CreateTable
CREATE TABLE "VENDEDOR" (
    "ID_VENDEDOR" TEXT NOT NULL,
    "ID_USUARIO" TEXT NOT NULL,
    "ID_EMPRESA" TEXT NOT NULL,
    "DESCRICAO_VENDEDOR" TEXT NOT NULL,

    CONSTRAINT "VENDEDOR_pkey" PRIMARY KEY ("ID_VENDEDOR")
);

-- CreateTable
CREATE TABLE "CLIENTE" (
    "ID_CLIENTE" TEXT NOT NULL,
    "ID_USUARIO" TEXT NOT NULL,
    "DESCRICAO_USUARIO" TEXT NOT NULL,
    "DOCUMENTO_USUARIO" TEXT NOT NULL,
    "TELEFONE_USUARIO" TEXT NOT NULL,

    CONSTRAINT "CLIENTE_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "PRODUTO" (
    "ID_PRODUTO" TEXT NOT NULL,
    "ID_EMPRESA" TEXT NOT NULL,
    "DESCRICAO_PRODUTO" TEXT NOT NULL,
    "VL_CUSTO" DOUBLE PRECISION NOT NULL,
    "VL_VENDA" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "PRODUTO_pkey" PRIMARY KEY ("ID_PRODUTO")
);

-- CreateTable
CREATE TABLE "VENDA" (
    "ID_VENDA" TEXT NOT NULL,
    "ID_CLIENTE" TEXT NOT NULL,
    "ID_VENDEDOR" TEXT NOT NULL,
    "ID_EMPRESA" TEXT NOT NULL,
    "VL_TOTAL" DOUBLE PRECISION NOT NULL,
    "VL_PAGO" DOUBLE PRECISION NOT NULL,
    "VL_ACRESCIMO" DOUBLE PRECISION NOT NULL,
    "VL_DESCONTO" DOUBLE PRECISION NOT NULL,
    "DT_VENDA" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VENDA_pkey" PRIMARY KEY ("ID_VENDA")
);

-- CreateTable
CREATE TABLE "VENDA_ITEM" (
    "ID_VENDA_ITEM" TEXT NOT NULL,
    "ID_VENDA" TEXT NOT NULL,
    "ID_PRODUTO" TEXT NOT NULL,
    "VL_TOTAL" DOUBLE PRECISION NOT NULL,
    "VL_CUSTO" DOUBLE PRECISION NOT NULL,
    "VL_ACRESCIMO" DOUBLE PRECISION NOT NULL,
    "VL_DESCONTO" DOUBLE PRECISION NOT NULL,
    "NR_QUANTIDADE" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "VENDA_ITEM_pkey" PRIMARY KEY ("ID_VENDA_ITEM")
);

-- AddForeignKey
ALTER TABLE "VENDEDOR" ADD CONSTRAINT "VENDEDOR_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO_SISTEMA"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENDEDOR" ADD CONSTRAINT "VENDEDOR_ID_EMPRESA_fkey" FOREIGN KEY ("ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENTE" ADD CONSTRAINT "CLIENTE_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO_SISTEMA"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PRODUTO" ADD CONSTRAINT "PRODUTO_ID_EMPRESA_fkey" FOREIGN KEY ("ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENDA" ADD CONSTRAINT "VENDA_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTE"("ID_CLIENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENDA" ADD CONSTRAINT "VENDA_ID_VENDEDOR_fkey" FOREIGN KEY ("ID_VENDEDOR") REFERENCES "VENDEDOR"("ID_VENDEDOR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENDA" ADD CONSTRAINT "VENDA_ID_EMPRESA_fkey" FOREIGN KEY ("ID_EMPRESA") REFERENCES "EMPRESA"("ID_EMPRESA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENDA_ITEM" ADD CONSTRAINT "VENDA_ITEM_ID_VENDA_fkey" FOREIGN KEY ("ID_VENDA") REFERENCES "VENDA"("ID_VENDA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VENDA_ITEM" ADD CONSTRAINT "VENDA_ITEM_ID_PRODUTO_fkey" FOREIGN KEY ("ID_PRODUTO") REFERENCES "PRODUTO"("ID_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;
